_BASE_: ../base.yaml
DATASET:
  ROOT: /datasets/ptgrecipes_quesadilla_pred
  VIDEO_PATTERN: /datasets/ptgrecipes-flat/quesadilla_*.mp4

DATA:
  VOCAB: 
    # - tortilla white flour circular: tortilla
    # - tortilla pizza plain circular: tortilla
    # - tortilla pizza circular paper_plate: tortilla
    - quesadilla pancake: tortilla
    - plate
  UNTRACKED_VOCAB:
    - tortilla plastic_bag packet ice_pack circular: package_tortilla
    - knife
    - jar
    - cutting board
    - toothpicks
    - floss
    - person

STEPS:
  - 