_BASE_: ../base.yaml
DATASET:
  ROOT: /datasets/ptgrecipes_tea_pred
  VIDEO_PATTERN: /datasets/ptgrecipes-flat/tea_*.mp4

DATA:
  VOCAB: 
    # - bowl cup: bowl
    - mug cup: mug
  UNTRACKED_VOCAB:
    - tea_bag
    - spoon
    - package
    - jar
    - honey_jar
    - jar_lid
    - water_bottle
    - measuring_cup

STEPS:
  - 