_BASE_: ../base.yaml
DATASET:
  ROOT: /datasets/xmem_eval
  VIDEO_PATTERN: /datasets/ptgrecipes_minieval/*.mp4

XMEM:
  FRAME_SIZE: 420
  CONFIG:
    # top_k: 15
    # mem_every: 30
    # deep_update_every: -1
    # enable_long_term: True
    # enable_long_term_count_usage: True
    # num_prototypes: 64
    # min_mid_term_frames: 6
    # max_mid_term_frames: 12
    # max_long_term_elements: 1000
    # tentative_frames: 4
    # tentative_age: 3
    # max_age: 60  # in steps
    min_iou: 0.4

DATA:
  # https://github.com/KaihuaTang/LVIS-for-mmdetection/blob/master/LVIS_utils.py
  VOCAB: 
    - tortilla
    # - tortilla white flour circular: tortilla
    # - tortilla pizza plain circular: tortilla
    # - tortilla pizza circular paper_plate: tortilla
    - bowl
    - microwave_oven
    - plate
    # - cup mug: cup
  UNTRACKED_VOCAB: lvis #[]
    # - tortilla plastic_bag packet ice_pack circular: package_tortilla
    # - measuring_cup hand_glass tachometer: measuring_cup
    # - kettle black atomizer: kettle
    # - scale_(measuring_instrument) cigarette_case electronic calculator iPad: scale
    # - thermometer pocketknife: thermometer
    # - coffee_grinder thermos_bottle canister cup: coffee_grinder
    # - paper paper_plate cupcake-liner cupcake muffin_liner seashell: coffee_filter
    # # - scraps wrap candle butter tape_(sticky_cloth_or_paper): tortilla_piece
    # # - wrap candle butter string_cheese square: tortilla_piece
    # - knife
    # # - peanut butter
    # # - jelly
    # - jar
    # # - cutting board
    # - toothpicks
    # - floss
