_BASE_: base.yaml
DATASET:
  ROOT: /datasets/annotation_final_eval
  VIDEO_PATTERN: /datasets/ptgrecipes-flat/*.mp4
  # STATES_CSV: /datasets/PTG Object State Labels - Step Annotations.csv
  # STATES_CSV: /datasets/PTG Object State Labels - Simple Step Annotations.csv
  STATES_CSV: /datasets/PTG Object State Labels - Step Annotations.csv
  META_CSV: /datasets/PTG Object State Labels - Metadata.csv

EVAL:
  USE_AUGMENTATIONS: True
  EMBEDDING_DBS:
   - /datasets/static_eval/clip_office_noaug.lancedb
  #  - /datasets/states_eval/clip_
  TRAIN_BASE_ROOT: /datasets/annotation_final
  TRAIN_BASE_CSV: config/train_static_base.txt
  TRAIN_CSV: config/train.txt
  VAL_CSV: config/val_mit.txt
  VAL_CSVS: 
   - config/val_mit.txt
   - config/val_nyu.txt