DATASET:
  VIDEO_PATTERN: /datasets/Milly/data/A*_pv.mp4
  ROOT: /datasets/Milly_pred3
  EMBEDDING_DIR: /datasets/Milly_pred3/embeddings/detections_tracker

DATA:
  VOCAB: 
    - tortilla, white flour, circular
  UNTRACKED_VOCAB:
    - knife
    - plate
    # - peanut butter
    # - jelly
    # - jar
    - person

STEPS:
  - name: 1. Place tortilla on cutting board.
    objects:
      - label: tortilla
        pre: plain
        mid: plain
        post: plain
  - name: 2. Use a butter knife to scoop nut butter from the jar. Spread nut butter onto tortilla, leaving 1/2 inch uncovered at the edges.
    objects:
      - label: tortilla
        pre: plain
        mid: peanut-butter[partial]
        post: peanut-butter[full]
      - label: knife
        pre: clean
        mid: dirty
        post: dirty
  - name: 3. Clean the knife by wiping with a paper towel.
    objects:
      - label: knife
        pre: dirty
        mid: dirty
        post: clean

