_BASE_: ../base.yaml
DATASET:
  ROOT: /datasets/ptgrecipes_coffee_pred
  VIDEO_PATTERN: /datasets/ptgrecipes-flat/coffee_*.mp4

DATA:
  VOCAB: 
    - mug cup: mug
    - mug
    - coffee_dripper pour_over_coffee mug: dripper
    # - cup vase teacup bowl: dripper
    # - cup mug chocolate_mousse cupcake
    - bowl
  UNTRACKED_VOCAB:
    - measuring_cup
    - scale_(measuring_instrument) cigarette_case electronic calculator iPad: scale
    - spoon
    - package
    - jar
    - honey_jar
    - jar_lid
    - water_bottle
    - kettle black atomizer: kettle
    - thermometer pocketknife: thermometer
    - coffee_grinder thermos_bottle canister cup: coffee_grinder
    - paper paper_plate cupcake-liner cupcake muffin_liner seashell: paper_filter
    - person
