_BASE_: ../base.yaml
DATASET:
  ROOT: /datasets/ptgrecipes_oatmeal_pred
  VIDEO_PATTERN: /datasets/ptgrecipes-flat/oatmeal_*.mp4

DATA:
  VOCAB: 
    - bowl
  UNTRACKED_VOCAB:
    - tea_bag
    - spoon

    - honey_jar
    - cinnamon_jar
    - jar_lid
    - jar

    - large_oatmeal_container
    - oatmeal_container
    - tupperware_lid

    - water_bottle
    - water_jug

    - measuring_cup

    - raisins
    - raisins_package
    - package

    - microwave
